INSERT INTO ACCOUNT (NUMBER) VALUES ('1');
INSERT INTO ACCOUNT (NUMBER) VALUES ('2');
INSERT INTO ACCOUNT (NUMBER) VALUES ('3');
INSERT INTO ACCOUNT (NUMBER) VALUES ('4');
INSERT INTO ACCOUNT (NUMBER) VALUES ('5');