INSERT INTO ACCOUNT (NUMBER) VALUES ('baseTest1');
INSERT INTO ACCOUNT (NUMBER) VALUES ('baseTest2');
INSERT INTO ACCOUNT (NUMBER) VALUES ('constraintViolationTest1');
INSERT INTO ACCOUNT (NUMBER) VALUES ('constraintViolationTest2');